name: flutter_gen_kit
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.6.0
  interact_cli: ^2.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
